# Ctrl + Alt + R
http://localhost:8000/

# Getting an object with spesific id
http://localhost:8000/4

# Getting spesific species
http://localhost:8000/?species=cat

# Getting adopted species
http://localhost:8000/?adopted=true

# Wrong route or id
http://localhost:8000/456